version: "3"

tasks:
  migrate:
    desc: Run DB migration
    cmds:
      - go run -v cmd/migration/main.go

  embed:
    desc: Run embedding
    dotenv: [".env"]
    cmds:
      - go run -v cmd/embed/main.go

  build:
    desc: Build RAG service
    cmds:
      - docker compose build

  up:
    desc: Launch RAG service
    cmds:
      - docker compose up -d

  down:
    desc: Launch RAG service
    cmds:
      - docker compose down

  split-openapi:
    desc: Splitter openapi
    cmds:
      - curl localhost:9999/openapi.json
